/* GitHub — where generated code lives.

   The product's rule is "the repo IS the build workspace": a run's code is a
   real repository with real commits, and every later stage (verify, deploy,
   test) reads from that repo rather than from a blob a worker kept in memory.
   That is what makes the pipeline resumable — a runner can die mid-stage and
   the next one picks up from the commit the last one wrote.

   Three operations matter:

     1. ensureRepo   — create the repo when it does not exist.
     2. latestSha    — read the branch tip, so a commit lands on top of the
                       previous one instead of replacing it.
     3. commitFiles  — write a whole tree of files in one commit, atomically.

   Everything here is honest about failure: a 401 is "this token cannot create
   a repo", a 422 on repo creation is "a repo with this name already exists"
   (so we adopt it), and a network error is a network error. The caller decides
   what each means for the run. */

import { resolveInfraToken } from "./settings";

const API = "https://api.github.com";

type GitAuth = { token: string; owner: string };

/** Which GitHub account the generated repo is created under.
    `scope` is who should own it; the function answers who the token *can* own
    it as, which is the same thing when the token is the owner's own. */
async function auth(owner: string): Promise<GitAuth | null> {
  const token = await resolveInfraToken("github");
  return token ? { token, owner } : null;
}

function headers(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "lastmile",
    "Content-Type": "application/json",
  };
}

export type RepoResult = {
  ok: boolean;
  repoUrl: string | null;
  /** null when the repo already existed — the run adopts it rather than fails */
  created: boolean | null;
  detail?: string;
};

/** Create the repository, or report that it already exists (which the caller
    treats as adoption, not failure — a retry must not fail because the first
    attempt got the commit through before the run crashed). */
export async function ensureRepo(
  owner: string,
  name: string,
  privateRepo: boolean,
): Promise<RepoResult> {
  const a = await auth(owner);
  if (!a) return { ok: false, repoUrl: null, created: null, detail: "no GitHub token is configured" };

  try {      const res = await fetch(`${API}/user/repos`, {
        method: "POST",
        headers: headers(a.token),
        body: JSON.stringify({
          name,
          description: "Generated by LastMile — one sentence in, verified link out",
          private: privateRepo,
          /* auto_init seeds the repo with a README commit. Without it the repo
             has no git state at all, and every Git Data API call against it —
             starting with the first blob of the first commit — is rejected with
             409 "Git Repository is empty", which is what killed every fresh
             run's code stage. A seeded repo commits cleanly immediately. */
          auto_init: true,
          has_issues: false,
          has_wiki: false,
          has_projects: false,
        }),
        signal: AbortSignal.timeout(30_000),
      });

    if (res.ok) {
      const body = (await res.json()) as { html_url?: string };
      return { ok: true, repoUrl: body.html_url ?? `https://github.com/${owner}/${name}`, created: true };
    }

    /* 422 with "already exists" is the common retry case — the repo made it on
       a prior attempt before the run died. Adopt it. */
    if (res.status === 422) {
      const body = (await res.json()) as { errors?: { message?: string }[] };
      const saysExists = (body.errors ?? []).some((e) =>
        /already exists/i.test(e.message ?? ""),
      );
      if (saysExists) {
        return { ok: true, repoUrl: `https://github.com/${owner}/${name}`, created: false };
      }
    }

    return {
      ok: false,
      repoUrl: null,
      created: null,
      detail: `GitHub answered HTTP ${res.status} creating ${owner}/${name}`,
    };
  } catch (error) {
    return {
      ok: false,
      repoUrl: null,
      created: null,
      detail: `could not reach GitHub: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/** The tip of the branch the run commits to, so a fix round lands on top of the
    previous commit instead of replacing it. */
export async function latestSha(owner: string, name: string, branch: string): Promise<string | null> {
  const a = await auth(owner);
  if (!a) return null;

  try {
    const res = await fetch(`${API}/repos/${owner}/${name}/git/ref/heads/${branch}`, {
      headers: headers(a.token),
      signal: AbortSignal.timeout(20_000),
    });
    if (!res.ok) return null;
    const body = (await res.json()) as { object?: { sha?: string } };
    return body.object?.sha ?? null;
  } catch {
    return null;
  }
}

export type CommitInput = {
  owner: string;
  name: string;
  branch?: string;
  files: { path: string; content: string }[];
  message: string;
};

export type CommitResult = {
  ok: boolean;
  sha: string | null;
  detail?: string;
};

/** GitHub's own error sentence, for details that say more than "HTTP 409".
    Consumes the response body, so only call it on the error path. */
async function reason(res: Response): Promise<string> {
  try {
    const body = (await res.json()) as { message?: string };
    return body.message ? ` — ${body.message}` : "";
  } catch {
    return "";
  }
}

/** Give an empty repo its first commit, via the Contents API — the one write
    that works when the repo has no git state. A README is enough: after it,
    blobs, trees and refs all behave. */
async function seedEmptyRepo(owner: string, name: string, branch: string): Promise<{ ok: boolean; detail?: string }> {
  const a = await auth(owner);
  if (!a) return { ok: false, detail: "no GitHub token is configured" };
  const res = await fetch(`${API}/repos/${owner}/${name}/contents/README.md`, {
    method: "PUT",
    headers: headers(a.token),
    body: JSON.stringify({
      message: "init: seeded by LastMile before the first build commit",
      content: Buffer.from(
        "# " + name + "\n\nGenerated by LastMile — one sentence in, verified link out.\n",
        "utf8",
      ).toString("base64"),
      branch,
    }),
    signal: AbortSignal.timeout(30_000),
  });
  if (!res.ok) {
    return { ok: false, detail: `could not seed the empty repo (HTTP ${res.status})${await reason(res)}` };
  }
  return { ok: true };
}

/** Write a tree of files and move the branch to it, in one atomic operation.
    Each file becomes a blob; the blobs become a tree; the tree becomes a
    commit whose parent is the branch tip; the branch moves to that commit. A
    failure at any step leaves the repo exactly as it was. */
export async function commitFiles(input: CommitInput): Promise<CommitResult> {
  const branch = input.branch ?? "main";
  const a = await auth(input.owner);
  if (!a) return { ok: false, sha: null, detail: "no GitHub token is configured" };

  try {
    /* 1. blobs — one per file. The tree API is the efficient path for a whole
          codebase, and it also dedupes identical blobs automatically.

          A 409 "Git Repository is empty" is recoverable: repos created before
          auto_init was turned on (or adopted mid-run) have no git state, and
          GitHub refuses blobs until a first commit exists. The Contents API is
          the one write that works on an empty repo, so it seeds the branch and
          the blob loop retries. */
    const blobs: { sha: string }[] = [];
    let bootstrapped = false;
    for (const file of input.files) {
      const res = await fetch(`${API}/repos/${input.owner}/${input.name}/git/blobs`, {
        method: "POST",
        headers: headers(a.token),
        body: JSON.stringify({ content: file.content, encoding: "utf-8" }),
        signal: AbortSignal.timeout(30_000),
      });
      if (!res.ok && res.status === 409 && !bootstrapped && /empty/i.test((await res.clone().text()) || "")) {
        bootstrapped = true;
        const seed = await seedEmptyRepo(input.owner, input.name, branch);
        if (!seed.ok) return { ok: false, sha: null, detail: seed.detail };
        const retry = await fetch(`${API}/repos/${input.owner}/${input.name}/git/blobs`, {
          method: "POST",
          headers: headers(a.token),
          body: JSON.stringify({ content: file.content, encoding: "utf-8" }),
          signal: AbortSignal.timeout(30_000),
        });
        if (!retry.ok) {
          return {
            ok: false,
            sha: null,
            detail: `GitHub rejected the blob for ${file.path} (HTTP ${retry.status})${await reason(retry)}`,
          };
        }
        const retryBody = (await retry.json()) as { sha?: string };
        if (!retryBody.sha) return { ok: false, sha: null, detail: `GitHub returned no sha for ${file.path}` };
        blobs.push({ sha: retryBody.sha });
        continue;
      }
      if (!res.ok) {
        return {
          ok: false,
          sha: null,
          detail: `GitHub rejected the blob for ${file.path} (HTTP ${res.status})${await reason(res)}`,
        };
      }
      const body = (await res.json()) as { sha?: string };
      if (!body.sha) return { ok: false, sha: null, detail: `GitHub returned no sha for ${file.path}` };
      blobs.push({ sha: body.sha });
    }

    /* 2. tree — the new tree's entries, based on the current tip so nothing
          that already exists is lost. */
    const parentSha = await latestSha(input.owner, input.name, branch);
    const treeBody = {
      tree: input.files.map((f, i) => ({
        path: f.path,
        mode: "100644" as const,
        type: "blob" as const,
        sha: blobs[i].sha,
      })),
      ...(parentSha ? { base_tree: parentSha } : {}),
    };
    const treeRes = await fetch(`${API}/repos/${input.owner}/${input.name}/git/trees`, {
      method: "POST",
      headers: headers(a.token),        body: JSON.stringify(treeBody),
        signal: AbortSignal.timeout(30_000),
      });
    if (!treeRes.ok) {
      return { ok: false, sha: null, detail: `GitHub rejected the tree (HTTP ${treeRes.status})${await reason(treeRes)}` };
    }
    const tree = (await treeRes.json()) as { sha?: string };
    if (!tree.sha) return { ok: false, sha: null, detail: "GitHub returned no tree sha" };

    /* 3. commit. */
    const commitRes = await fetch(`${API}/repos/${input.owner}/${input.name}/git/commits`, {
      method: "POST",
      headers: headers(a.token),
      body: JSON.stringify({
        message: input.message,
        tree: tree.sha,
        ...(parentSha ? { parents: [parentSha] } : {}),
      }),
      signal: AbortSignal.timeout(30_000),
    });
    if (!commitRes.ok) {
      return { ok: false, sha: null, detail: `GitHub rejected the commit (HTTP ${commitRes.status})` };
    }
    const commit = (await commitRes.json()) as { sha?: string };
    if (!commit.sha) return { ok: false, sha: null, detail: "GitHub returned no commit sha" };

    /* 4. move the branch. The first commit has no ref yet, so it needs a
          create rather than an update — the API distinguishes the two. */
    const refUrl = `${API}/repos/${input.owner}/${input.name}/git/refs`;
    const refBody = JSON.stringify({ ref: `refs/heads/${branch}`, sha: commit.sha });

    let refRes: Response;
    if (parentSha) {
      /* The qualified form is required here: PATCH /git/refs/{ref} does not
         resolve a bare branch name — "main" answers 422 "Reference does not
         exist" even while the ref plainly exists (verified live). "heads/main"
         is the form the endpoint documents and accepts. */
      refRes = await fetch(`${refUrl}/heads/${branch}`, {
        method: "PATCH",
        headers: headers(a.token),
        body: JSON.stringify({ sha: commit.sha, force: false }),
        signal: AbortSignal.timeout(30_000),
      });
    } else {
      refRes = await fetch(refUrl, {
        method: "POST",
        headers: headers(a.token),
        body: refBody,
        signal: AbortSignal.timeout(30_000),
      });
    }

    if (!refRes.ok) {
      return { ok: false, sha: null, detail: `GitHub rejected the ref update (HTTP ${refRes.status})${await reason(refRes)}` };
    }

    return { ok: true, sha: commit.sha };
  } catch (error) {
    return {
      ok: false,
      sha: null,
      detail: `could not reach GitHub: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}