import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { chromium, type Browser, type BrowserContext, type Page } from "playwright-core";
import { agentChat } from "@/lib/ai/registry";
import { asObjectArray, asString, extractJson } from "@/lib/ai/json";
import { browserUseConfigured, runBrowserUseTask } from "@/lib/browser-use";
import type { Emit, MasterBuildPrompt } from "./prompt-engineer";
import { artifactsDir } from "@/lib/platform/workspace";
import type { PlanId } from "@/lib/platform/settings";

/* Testing Agent — live QA. It drives the DEPLOYED URL with a real browser,
   exactly the way the spec promised verification would: every flow from the
   master prompt, navigation, forms, console errors, responsive smoke.

   Test plans are generated by the model from the master prompt (deterministic
   fallback: load, title, console, screenshot per flow route), then executed
   step-by-step. Failures become structured defect reports — the quality
   loop's queue. Screenshots land in the run's artifacts directory. */

/* ———————————————————————— browser discovery ———————————————————————— */

const CANDIDATES = [
  // windows
  "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
  "C:/Program Files/Microsoft/Edge/Application/msedge.exe",
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
  process.env.LOCALAPPDATA ? process.env.LOCALAPPDATA + "/Google/Chrome/Application/chrome.exe" : "",
  // macOS
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
  "/Applications/Chromium.app/Contents/MacOS/Chromium",
  // linux
  "/usr/bin/google-chrome",
  "/usr/bin/google-chrome-stable",
  "/usr/bin/chromium-browser",
  "/usr/bin/chromium",
  "/usr/bin/msedge",
  "/snap/bin/chromium",
].filter(Boolean);

export function findBrowser(): string | null {
  for (const p of CANDIDATES) {
    try {
      if (existsSync(p)) return p;
    } catch {
      /* keep looking */
    }
  }
  // PATH lookup as a last resort
  const which = spawnSync(process.platform === "win32" ? "where" : "which", ["chromium", "google-chrome", "chrome", "msedge"], { encoding: "utf8" });
  const first = which.stdout?.split("\n")[0]?.trim();
  return first && first.length > 0 && existsSync(first) ? first : null;
}

/* ———————————————————————— test plans ———————————————————————— */

export type TestStep =
  | { action: "goto"; url: string }
  | { action: "click"; selector: string }
  | { action: "fill"; selector: string; value: string }
  | { action: "press"; key: string }
  | { action: "reload" }
  | { action: "expectText"; text: string }
  | { action: "expectSelector"; selector: string }
  | { action: "expectUrl"; contains: string }
  | { action: "resize"; width: number; height: number };

export type FlowPlan = { name: string; steps: TestStep[] };

export type FlowResult = {
  name: string;
  passed: boolean;
  assertions: number;
  attempts: number;
  durationMs: number;
  failure: string | null;
};

export type TestReport = {
  flows: FlowResult[];
  consoleErrors: string[];
  screenshots: string[];
  passedAssertions: number;
  totalAssertions: number;
  score: number; // 0-100
  browser: string;
};

const PLAN_SYSTEM = `You are the Testing Agent of LastMile. You turn a product's must-have features into concrete browser test plans against its live URL.

Rules:
- Steps run sequentially on one page. Use simple, robust CSS selectors (ids, roles, aria-labels, data-testid, text-less classes last).
- goto URLs are paths starting with "/" (the base URL is prepended).
- Always end a flow with at least one expectText or expectSelector that proves the outcome.
- Test what a user would do: fill real values, submit, check the visible result.
- 2-4 flows total; each 3-8 steps. No step that needs external services.

THE USER'S PROMPT IS THE ENTIRE SPEC — nothing may be added to it and nothing may be required beyond it. If the product is "a page that says X", then showing exactly X is a PASS, not a thin page: never test for word counts, "more than a few words", "real content", rich text, extra sections, or features the prompt did not ask for. A minimal page that satisfies a minimal prompt is a perfect product. When a must-have feature names exact text, use expectText with that exact text so the check proves the right thing.`;

const FALLBACK_PLAN: FlowPlan[] = [
  {
    name: "Home page loads with content",
    steps: [
      { action: "goto", url: "/" },
      { action: "expectSelector", selector: "main, body" },
      { action: "expectText", text: "" }, // replaced at runtime: any non-empty body
    ],
  },
  {
    name: "No console errors on load and reload",
    steps: [
      { action: "goto", url: "/" },
      { action: "reload" },
      { action: "expectSelector", selector: "main, body" },
    ],
  },
];

async function planTests(
  master: MasterBuildPrompt,
  plan: PlanId,
  emit: Emit,
): Promise<FlowPlan[]> {
  const must = master.features.filter((f) => f.priority === "must");
  try {
    const res = await agentChat(
      plan,
      "test",
      [
        { role: "system", content: PLAN_SYSTEM },
        {
          role: "user",
          content: `Product: ${master.productName} — ${master.tagline}\nPages: ${master.pages.map((p) => p.path + " (" + p.purpose + ")").join(", ")}\nMust-have features:\n${must.map((f) => `- ${f.name}: ${f.description}`).join("\n")}\nEdge cases: ${master.edgeCases.join("; ")}\n\nWrite the test plans. Return ONLY:\n{"flows": [{"name": "...", "steps": [{"action": "goto|click|fill|press|reload|expectText|expectSelector|expectUrl|resize", ...}]}]}\nStep fields: goto{url}, click{selector}, fill{selector,value}, press{key}, expectText{text}, expectSelector{selector}, expectUrl{contains}, resize{width,height}, reload{}.`,
        },
      ],
      { temperature: 0.3, maxTokens: 2600, json: true, timeoutMs: 90_000 },
    );
    const json = extractJson<{ flows?: unknown }>(res.text);
    const flows = (json ? asObjectArray(json.flows, 5) : [])
      .map((f) => ({
        name: asString(f.name),
        steps: asObjectArray(f.steps, 12)
          .map((s): TestStep | null => {
            const action = asString(s.action);
            if (action === "goto") return { action, url: asString(s.url) || "/" };
            if (action === "click") return { action, selector: asString(s.selector) };
            if (action === "fill") return { action, selector: asString(s.selector), value: asString(s.value) };
            if (action === "press") return { action, key: asString(s.key) || "Enter" };
            if (action === "expectText") return { action, text: asString(s.text) };
            if (action === "expectSelector") return { action, selector: asString(s.selector) };
            if (action === "expectUrl") return { action, contains: asString(s.contains) };
            if (action === "resize") return { action, width: Number(s.width) || 390, height: Number(s.height) || 844 };
            return null;
          })
          .filter((s): s is TestStep => s !== null),
      }))
      .filter((f) => f.name && f.steps.length > 0);
    if (flows.length === 0) throw new Error("no usable flows");
    await emit({ kind: "info", line: `-> ${flows.length} test flows planned from the master prompt` });
    return flows;
  } catch (err) {
    await emit({
      kind: "warn",
      line: "-> model test plan unavailable (" + (err instanceof Error ? err.message.slice(0, 100) : String(err)) + ") — running the baseline suite",
    });
    return FALLBACK_PLAN;
  }
}

/* ———————————————————————— execution ———————————————————————— */

const CHROME_ARGS = ["--enable-unsafe-swiftshader", "--use-angle=swiftshader", "--no-first-run", "--disable-features=DialMediaRouteProvider", "--disable-gpu-sandbox"];

async function runFlow(
  page: Page,
  baseUrl: string,
  flow: FlowPlan,
  shots: string[],
  shotDir: string,
  tag: string,
): Promise<FlowResult> {
  const started = Date.now();
  let assertions = 0;
  let failure: string | null = null;
  let currentUrl = baseUrl;

  for (const [i, step] of flow.steps.entries()) {
    try {
      switch (step.action) {
        case "goto":
          currentUrl = step.url.startsWith("http") ? step.url : baseUrl.replace(/\/$/, "") + step.url;
          await page.goto(currentUrl, { waitUntil: "domcontentloaded", timeout: 20_000 });
          break;
        case "reload":
          await page.reload({ waitUntil: "domcontentloaded", timeout: 20_000 });
          break;
        case "click":
          await page.locator(step.selector).first().click({ timeout: 8000 });
          break;
        case "fill":
          await page.locator(step.selector).first().fill(step.value, { timeout: 8000 });
          break;
        case "press":
          await page.keyboard.press(step.key);
          break;
        case "resize":
          await page.setViewportSize({ width: step.width, height: step.height });
          break;
        case "expectText": {
          // empty text = "page has any content"
          if (step.text) {
            await page.getByText(step.text, { exact: false }).first().waitFor({ timeout: 8000 });
          } else {
            const body = await page.locator("body").innerText({ timeout: 8000 });
            if (body.trim().length < 10) throw new Error("page body is nearly empty");
          }
          break;
        }
        case "expectSelector":
          await page.locator(step.selector).first().waitFor({ timeout: 8000 });
          break;
        case "expectUrl":
          if (!page.url().includes(step.contains)) throw new Error("expected url to contain " + JSON.stringify(step.contains) + ", got " + page.url());
          break;
      }
      assertions++;
    } catch (err) {
      failure = `step ${i + 1} (${step.action}) failed: ${err instanceof Error ? err.message.split("\n")[0].slice(0, 220) : String(err)}`;
      break;
    }
  }

  // screenshot regardless of outcome — proof either way
  try {
    const path = join(shotDir, `${tag}.png`);
    await page.screenshot({ path, fullPage: false });
    shots.push(`${tag}.png`);
  } catch {
    /* headless screenshot failures are not test failures */
  }

  return {
    name: flow.name,
    passed: failure === null,
    assertions,
    attempts: 1,
    durationMs: Date.now() - started,
    failure,
  };
}

/* ———————————————————————— cloud execution (browser-use) ———————————————————————— */

/** One test flow → one natural-language cloud session. The agent explores the
    real DOM (better than brittle CSS in a scripted runner), but it must end
    with a machine-parsable verdict line. */
function flowToTask(baseUrl: string, flow: FlowPlan): string {
  const base = baseUrl.replace(/\/+$/, "");
  const abs = (u: string) => (u.startsWith("http") ? u : base + (u.startsWith("/") ? u : "/" + u));
  const steps: string[] = [];
  for (const step of flow.steps) {
    switch (step.action) {
      case "goto":
        steps.push(`Open ${abs(step.url)} and wait for it to load`);
        break;
      case "reload":
        steps.push("Reload the current page and wait for it to finish loading");
        break;
      case "click":
        steps.push(`Click the first element matching the CSS selector \`${step.selector}\``);
        break;
      case "fill":
        steps.push(`Clear, then type \`${step.value}\` into the field matching the CSS selector \`${step.selector}\``);
        break;
      case "press":
        steps.push(`Press the ${step.key} key`);
        break;
      case "resize":
        steps.push(`Resize the browser viewport to exactly ${step.width}x${step.height}`);
        break;
      case "expectText":
        steps.push(
          step.text
            ? `Verify the text "${step.text}" is visible on the page`
            : // the fallback must not invent a content-volume rule: a page the
              // user asked to be two words long fails "more than a few words"
              // through no fault of its own. An empty-text check only asserts
              // that the document rendered at all.
              "Verify the page has rendered visible content (the body is not blank)",
        );
        break;
      case "expectSelector":
        steps.push(`Verify an element matching the CSS selector \`${step.selector}\` exists`);
        break;
      case "expectUrl":
        steps.push(`Verify the current URL contains "${step.contains}"`);
        break;
    }
  }
  if (!flow.steps.some((s) => s.action === "goto")) steps.unshift(`Open ${base} and wait for it to load`);

  return [
    `You are QA-testing a live web app rooted at ${base}.`,
    `Flow under test: "${flow.name}"`,
    "",
    ...steps.map((s, i) => `${i + 1}. ${s}`),
    "",
    "Execute every step in order against the real page. If a step is impossible or a check fails, note why and continue with the remaining steps where it still makes sense.",
    "Judge the app ONLY by the checks above — do not invent extra requirements (word counts, content volume, features beyond the list). A minimal app that passes every check is a full pass.",
    "End your reply with exactly one final line:",
    "QA: PASS",
    "if every step succeeded, or",
    "QA: FAIL: <one short line saying what failed>",
    "if anything failed. No other trailing text.",
  ].join("\n");
}

function parseVerdict(output: string): { passed: boolean; reason: string | null } {
  const fail = output.match(/QA:\s*FAIL[:\s]*([\s\S]*)/i);
  if (fail) return { passed: false, reason: (fail[1] || "unspecified").trim().split("\n")[0].slice(0, 220) || "unspecified" };
  if (/QA:\s*PASS/i.test(output)) return { passed: true, reason: null };
  // the agent finished but ignored the reporting contract — that is a fail,
  // never a silent pass
  return { passed: false, reason: "cloud agent did not return a QA verdict — output: " + output.slice(0, 140) };
}

async function runCloudFlow(
  liveUrl: string,
  flow: FlowPlan,
  emit: Emit,
): Promise<{ flow: FlowResult; session: { sessionId: string; liveUrl: string | null; recordingUrl: string | null } | null }> {
  const started = Date.now();
  try {
    const res = await runBrowserUseTask(flowToTask(liveUrl, flow), { timeoutMs: 300_000 });
    const verdict = parseVerdict(res.output);
    if (res.liveUrl) await emit({ kind: "info", line: `-> watch: ${res.liveUrl}` });
    return {
      flow: {
        name: flow.name,
        passed: verdict.passed,
        assertions: 1, // the cloud agent runs the whole flow per session; its verdict is the assertion
        attempts: 1,
        durationMs: res.elapsedMs,
        failure: verdict.reason,
      },
      session: { sessionId: res.sessionId, liveUrl: res.liveUrl, recordingUrl: res.recordingUrl },
    };
  } catch (err) {
    return {
      flow: {
        name: flow.name,
        passed: false,
        assertions: 0,
        attempts: 1,
        durationMs: Date.now() - started,
        failure: "cloud session failed: " + (err instanceof Error ? err.message.split("\n")[0].slice(0, 180) : String(err)),
      },
      session: null,
    };
  }
}

/** Cloud QA path: no local Chromium needed. Any infra failure on the FIRST
    flow throws so testLive can fall back to the local browser; later failures
    are recorded as failed flows, not crashes. */
async function testLiveCloud(
  runId: string,
  liveUrl: string,
  master: MasterBuildPrompt,
  plan: PlanId,
  emit: Emit,
): Promise<TestReport> {
  await emit({ kind: "info", line: "-> browser: browser-use cloud — no local Chromium needed" });

  const shotDir = artifactsDir(runId);
  const plans = await planTests(master, plan, emit);
  const flows: FlowResult[] = [];
  const sessions: { name: string; sessionId: string; liveUrl: string | null; recordingUrl: string | null }[] = [];

  for (const [i, flow] of plans.entries()) {
    await emit({ kind: "info", line: `-> testing: ${flow.name}` });
    const result = await runCloudFlow(liveUrl, flow, emit);
    if (i === 0 && result.session === null) {
      throw new Error(result.flow.failure ?? "cloud session failed");
    }
    if (result.session) sessions.push({ name: flow.name, ...result.session });
    flows.push(result.flow);
    await emit({
      kind: result.flow.passed ? "success" : "error",
      line: result.flow.passed
        ? `[PASS] ${flow.name} — cloud session — ${(result.flow.durationMs / 1000).toFixed(1)}s`
        : `[FAIL] ${flow.name} — ${result.flow.failure}`,
    });
  }

  // responsive smoke — same promise the local path checks, as a cloud task
  await emit({ kind: "info", line: "-> responsive smoke — 390×844 (cloud)" });
  const mobile = await runCloudFlow(
    liveUrl,
    {
      name: "Responsive — no horizontal overflow at 390px",
      steps: [
        { action: "goto", url: "/" },
        { action: "resize", width: 390, height: 844 },
        { action: "reload" },
        { action: "expectText", text: "" },
      ],
    },
    emit,
  );
  if (mobile.session) sessions.push({ name: mobile.flow.name, ...mobile.session });
  const overflow = mobile.flow.failure?.match(/by\s+(\d+)\s*px/i);
  if (!mobile.flow.passed && overflow) mobile.flow.failure = `page overflows viewport horizontally by ${overflow[1]}px at 390px width`;
  flows.push(mobile.flow);
  await emit({
    kind: mobile.flow.passed ? "success" : "error",
    line: mobile.flow.passed ? "[PASS] responsive — fits 390px" : `[FAIL] responsive — ${mobile.flow.failure}`,
  });

  writeFileSync(join(shotDir, "browser-use.json"), JSON.stringify(sessions, null, 2));

  const passedFlows = flows.filter((f) => f.passed).length;
  const score = flows.length > 0 ? Math.round((passedFlows / flows.length) * 100) : 0;
  await emit({
    kind: score === 100 ? "success" : "warn",
    line: `-> live QA (cloud) — ${passedFlows}/${flows.length} flows passing — score ${score}/100`,
  });

  const report: TestReport = {
    flows,
    consoleErrors: [], // cloud sessions do not expose the page console
    screenshots: [], // session replays live in browser-use.json instead
    passedAssertions: flows.filter((f) => f.passed).reduce((a, f) => a + f.assertions, 0),
    totalAssertions: flows.reduce((a, f) => a + f.assertions, 0),
    score,
    browser: "browser-use cloud",
  };
  writeFileSync(join(shotDir, "report.json"), JSON.stringify(report, null, 2));
  return report;
}

export async function testLive(
  runId: string,
  liveUrl: string,
  master: MasterBuildPrompt,
  plan: PlanId,
  emit: Emit,
): Promise<TestReport> {
  await emit({ kind: "command", line: `$ lastmile test — ${liveUrl.replace(/^https?:\/\//, "")}` });

  // cloud first — a machine without Chrome/Edge can still run live QA
  if (browserUseConfigured()) {
    try {
      return await testLiveCloud(runId, liveUrl, master, plan, emit);
    } catch (err) {
      await emit({
        kind: "warn",
        line: "-> browser-use cloud unavailable (" + (err instanceof Error ? err.message.slice(0, 140) : String(err)) + ") — falling back to the local browser",
      });
    }
  }

  const executablePath = findBrowser();
  if (!executablePath) {
    throw new Error(
      "no Chromium-family browser found for live testing — install Chrome or Edge, or set PLAYWRIGHT_EXECUTABLE_PATH",
    );
  }
  const browser: Browser = await chromium.launch({ executablePath, headless: true, args: CHROME_ARGS });
  await emit({ kind: "info", line: "-> browser online — " + executablePath.split(/[\\/]/).pop() });

  const shotDir = artifactsDir(runId);
  const shots: string[] = [];
  const consoleErrors: string[] = [];

  try {
    const plans = await planTests(master, plan, emit);
    const context: BrowserContext = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    const page = await context.newPage();

    page.on("console", (msg) => {
      if (msg.type() === "error") consoleErrors.push(msg.text().slice(0, 300));
    });
    page.on("pageerror", (err) => consoleErrors.push("pageerror: " + String(err).slice(0, 300)));
    page.on("requestfailed", (req) => {
      if (!req.url().includes("favicon")) consoleErrors.push("request failed: " + req.url().slice(0, 160));
    });

    const flows: FlowResult[] = [];
    for (const [i, flow] of plans.entries()) {
      await emit({ kind: "info", line: `-> testing: ${flow.name}` });
      const result = await runFlow(page, liveUrl, flow, shots, shotDir, `flow-${i + 1}`);
      flows.push(result);
      await emit({
        kind: result.passed ? "success" : "error",
        line: result.passed
          ? `[PASS] ${flow.name} — ${result.assertions} assertion${result.assertions === 1 ? "" : "s"} — ${(result.durationMs / 1000).toFixed(1)}s`
          : `[FAIL] ${flow.name} — ${result.failure}`,
      });
    }

    // responsive smoke: the master prompt promises 390px works — check it loads
    await emit({ kind: "info", line: "-> responsive smoke — 390×844" });
    await page.setViewportSize({ width: 390, height: 844 });
    try {
      await page.goto(liveUrl, { waitUntil: "domcontentloaded", timeout: 20_000 });
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
      if (overflow > 24) {
        flows.push({
          name: "Responsive — no horizontal overflow at 390px",
          passed: false,
          assertions: 1,
          attempts: 1,
          durationMs: 0,
          failure: `page overflows viewport horizontally by ${Math.round(overflow)}px at 390px width`,
        });
        await emit({ kind: "error", line: `[FAIL] responsive — overflows by ${Math.round(overflow)}px` });
      } else {
        flows.push({
          name: "Responsive — no horizontal overflow at 390px",
          passed: true,
          assertions: 1,
          attempts: 1,
          durationMs: 0,
          failure: null,
        });
        await emit({ kind: "success", line: "[PASS] responsive — fits 390px" });
      }
      await page.screenshot({ path: join(shotDir, "mobile.png") }).catch(() => undefined);
      shots.push("mobile.png");
    } catch (err) {
      flows.push({
        name: "Responsive — no horizontal overflow at 390px",
        passed: false,
        assertions: 0,
        attempts: 1,
        durationMs: 0,
        failure: "mobile load failed: " + (err instanceof Error ? err.message.split("\n")[0].slice(0, 160) : String(err)),
      });
    }

    await context.close();

    const totalAssertions = flows.reduce((a, f) => a + f.assertions, 0);
    const passedFlows = flows.filter((f) => f.passed).length;
    const criticalConsole = consoleErrors.filter((e) => !/favicon|sourcemap|Download the React DevTools/i.test(e)).length;

    // honest score: flow passes dominate; console errors subtract
    const flowScore = flows.length > 0 ? (passedFlows / flows.length) * 92 : 0;
    const consolePenalty = Math.min(8, criticalConsole * 2);
    const score = Math.max(0, Math.round(flowScore + (criticalConsole === 0 ? 8 : 0) - consolePenalty));

    await emit({
      kind: score === 100 ? "success" : "warn",
      line: `-> live QA — ${passedFlows}/${flows.length} flows passing, ${totalAssertions} assertions, ${criticalConsole} console errors — score ${score}/100`,
    });

    const report: TestReport = {
      flows,
      consoleErrors: consoleErrors.slice(0, 20),
      screenshots: shots,
      passedAssertions: flows.filter((f) => f.passed).reduce((a, f) => a + f.assertions, 0),
      totalAssertions,
      score,
      browser: executablePath.split(/[\\/]/).pop() ?? "chromium",
    };
    writeFileSync(join(shotDir, "report.json"), JSON.stringify(report, null, 2));
    return report;
  } finally {
    await browser.close().catch(() => undefined);
  }
}
