#!/usr/bin/env node
/* Pack the Next.js (turbopack) production build for Zoho Catalyst AppSail.

     npm run build && node scripts/catalyst-pack.mjs

   The turbopack build bundles every server dependency into .next/server/chunks
   (verified: chunks contain no require("<pkg>") externals), so the deployable
   needs only:

     .next/            slim build output (server/, static/, manifests —
                       no cache/dev/trace/turbopack/types)
     node_modules/next the Next runtime (`next start` and its compiled deps)
     public/           static assets (created even when empty)
     .env              runtime env vars, sourced from .env.local minus AUTH_URL
                       (which pins Auth.js to localhost and would poison OAuth
                       callbacks on the deployed host; AUTH_TRUST_HOST covers it)

   Also writes app-config.json (gitignored — carries secrets) using the CLI's
   own schema (command / build_path / stack / env_variables / memory). AppSail
   injects the listen port as X_ZOHO_CATALYST_LISTEN_PORT.
*/
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const outDir = join(root, "deployable");
const nextDir = join(root, ".next");

if (!existsSync(join(nextDir, "required-server-files.json"))) {
  console.error("No production build found — run `npm run build` first.");
  process.exit(1);
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

/* slim .next: whitelist directories + root manifest files */
const NEXT_COPY_DIRS = ["server", "static", "build"];
for (const dir of NEXT_COPY_DIRS) {
  if (existsSync(join(nextDir, dir))) cpSync(join(nextDir, dir), join(outDir, ".next", dir), { recursive: true });
}
for (const entry of readdirSync(nextDir, { withFileTypes: true })) {
  if (!entry.isFile()) continue;
  if (entry.name.endsWith(".nft.json") || entry.name === "trace") continue;
  cpSync(join(nextDir, entry.name), join(outDir, ".next", entry.name));
}

/* The runtime packages `next start` itself needs — the app's own server
   dependencies are bundled into .next/server/chunks by turbopack. Copy next's
   full dependency closure (npm's flat tree keeps them all in root). */
const RUNTIME_ROOTS = ["next", "react", "react-dom"];
function copyPackage(pkg) {
  const from = join(root, "node_modules", pkg);
  const to = join(outDir, "node_modules", pkg);
  if (existsSync(to)) return;
  if (!existsSync(from)) {
    console.error("node_modules/" + pkg + " is missing — run `npm install`.");
    process.exit(1);
  }
  cpSync(from, to, { recursive: true });
  const manifest = JSON.parse(readFileSync(join(from, "package.json"), "utf8"));
  for (const dep of Object.keys(manifest.dependencies ?? {})) copyPackage(dep);
}
for (const pkg of RUNTIME_ROOTS) copyPackage(pkg);

/* public/ (Next expects it to exist) */
mkdirSync(join(outDir, "public"), { recursive: true });

/* runtime env from .env.local */
const env = {};
for (const line of readFileSync(join(root, ".env.local"), "utf8").split(/\r?\n/)) {
  const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
  if (!m || !m[2]) continue;
  let v = m[2];
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
  env[m[1]] = v;
}
delete env.AUTH_URL;
env.AUTH_TRUST_HOST ??= "true";
writeFileSync(
  join(outDir, ".env"),
  Object.entries(env)
    .map(([k, v]) => k + "=" + v)
    .join("\n") + "\n",
);

/* Port shim — AppSail injects its listen port as X_ZOHO_CATALYST_LISTEN_PORT.
   A JS shim (no shell, no ${} expansion) is the only startup command that is
   guaranteed to survive however AppSail spawns it. */
writeFileSync(
  join(outDir, "start.js"),
  `/* Generated by scripts/catalyst-pack.mjs — AppSail startup shim. */
const { spawn } = require("node:child_process");
const port = String(process.env.X_ZOHO_CATALYST_LISTEN_PORT || process.env.PORT || "3000");
process.env.PORT = port;
process.env.HOSTNAME = process.env.HOSTNAME || "0.0.0.0";
const child = spawn(process.execPath, ["node_modules/next/dist/bin/next", "start", "-p", port], {
  stdio: "inherit",
  env: process.env,
  cwd: __dirname,
});
child.on("exit", (code, signal) => process.exit(code ?? (signal ? 1 : 0)));
`,
);

/* app-config.json — the CLI's own schema */
const appConfig = {
  command: "node start.js",
  build_path: "deployable",
  stack: "node20",
  env_variables: env,
  memory: 1024,
  scripts: {},
};
writeFileSync(join(root, "app-config.json"), JSON.stringify(appConfig, null, 2) + "\n");

function dirSize(p) {
  let total = 0;
  for (const entry of readdirSync(p, { withFileTypes: true })) {
    const full = join(p, entry.name);
    total += entry.isDirectory() ? dirSize(full) : statSync(full).size;
  }
  return total;
}
const mb = (dirSize(outDir) / 2 ** 20).toFixed(1);
console.log(`deployable/ assembled at ${outDir} (${mb} MB)`);
console.log(`app-config.json written (${Object.keys(env).length} env vars, AUTH_URL excluded)`);
